/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.biroscadocalvino;

import java.util.logging.Level;
import java.util.logging.Logger;
import telas.telasExibicao.VisualizarAcampantes;
import telas.telasExibicao.VisualizarProdutos;
import telas.telasExibicao.VisualizarSaldoAcampantes;
import telas.telasInt.TelaVenda;

/**
 *
 * @author davidson.filho
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form tela
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar = new javax.swing.JMenuBar();
        jMCads = new javax.swing.JMenu();
        jMICadastrarAcampante = new javax.swing.JMenuItem();
        jMICadastrarProduto = new javax.swing.JMenuItem();
        jMILogout = new javax.swing.JMenuItem();
        jMEfetuar = new javax.swing.JMenu();
        jMIEfetuarVenda = new javax.swing.JMenuItem();
        jMIDeposito = new javax.swing.JMenuItem();
        jMAlteracoes = new javax.swing.JMenu();
        jMIAlterarAcampante = new javax.swing.JMenuItem();
        jMIAlterarProduto = new javax.swing.JMenuItem();
        jMDeletes = new javax.swing.JMenu();
        jMIDeleteAcampante = new javax.swing.JMenuItem();
        jMIDeleteProduto = new javax.swing.JMenuItem();
        Vizualizar = new javax.swing.JMenu();
        jMIVisualizarAcampantes = new javax.swing.JMenuItem();
        jMIVisualizarProdutos = new javax.swing.JMenuItem();
        jMIVisualizarSaldo = new javax.swing.JMenuItem();
        jMIVisualizarVendas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jMCads.setText("Cadastros");

        jMICadastrarAcampante.setText("Acampante");
        jMICadastrarAcampante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMICadastrarAcampanteActionPerformed(evt);
            }
        });
        jMCads.add(jMICadastrarAcampante);

        jMICadastrarProduto.setText("Produto");
        jMICadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMICadastrarProdutoActionPerformed(evt);
            }
        });
        jMCads.add(jMICadastrarProduto);

        jMILogout.setText("Log out");
        jMILogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMILogoutActionPerformed(evt);
            }
        });
        jMCads.add(jMILogout);

        jMenuBar.add(jMCads);

        jMEfetuar.setText("Efetuar");

        jMIEfetuarVenda.setText("Venda");
        jMIEfetuarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIEfetuarVendaActionPerformed(evt);
            }
        });
        jMEfetuar.add(jMIEfetuarVenda);

        jMIDeposito.setText("Depósito");
        jMIDeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIDepositoActionPerformed(evt);
            }
        });
        jMEfetuar.add(jMIDeposito);

        jMenuBar.add(jMEfetuar);

        jMAlteracoes.setText("Alterações");

        jMIAlterarAcampante.setText("Acampante");
        jMIAlterarAcampante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIAlterarAcampanteActionPerformed(evt);
            }
        });
        jMAlteracoes.add(jMIAlterarAcampante);

        jMIAlterarProduto.setText("Produto");
        jMIAlterarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIAlterarProdutoActionPerformed(evt);
            }
        });
        jMAlteracoes.add(jMIAlterarProduto);

        jMenuBar.add(jMAlteracoes);

        jMDeletes.setText("Deletar");

        jMIDeleteAcampante.setText("Acampante");
        jMIDeleteAcampante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIDeleteAcampanteActionPerformed(evt);
            }
        });
        jMDeletes.add(jMIDeleteAcampante);

        jMIDeleteProduto.setText("Produto");
        jMIDeleteProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIDeleteProdutoActionPerformed(evt);
            }
        });
        jMDeletes.add(jMIDeleteProduto);

        jMenuBar.add(jMDeletes);

        Vizualizar.setText("Visualizar");

        jMIVisualizarAcampantes.setText("Acampantes");
        jMIVisualizarAcampantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIVisualizarAcampantesActionPerformed(evt);
            }
        });
        Vizualizar.add(jMIVisualizarAcampantes);

        jMIVisualizarProdutos.setText("Produtos");
        jMIVisualizarProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIVisualizarProdutosActionPerformed(evt);
            }
        });
        Vizualizar.add(jMIVisualizarProdutos);

        jMIVisualizarSaldo.setText("Saldo");
        jMIVisualizarSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIVisualizarSaldoActionPerformed(evt);
            }
        });
        Vizualizar.add(jMIVisualizarSaldo);

        jMIVisualizarVendas.setText("Vendas");
        jMIVisualizarVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIVisualizarVendasActionPerformed(evt);
            }
        });
        Vizualizar.add(jMIVisualizarVendas);

        jMenuBar.add(Vizualizar);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 427, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMICadastrarAcampanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMICadastrarAcampanteActionPerformed
        CadastroAcampante screen = new CadastroAcampante();
        screen.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMICadastrarAcampanteActionPerformed

    private void jMICadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMICadastrarProdutoActionPerformed
        CadastroProduto screen = new CadastroProduto();
        screen.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMICadastrarProdutoActionPerformed

    private void jMILogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMILogoutActionPerformed
        TelaLogin screen = new TelaLogin();
        screen.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMILogoutActionPerformed

    private void jMIEfetuarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIEfetuarVendaActionPerformed
        TelaVenda screen;
        try {
            screen = new TelaVenda();
            screen.setVisible(true);
            dispose();
        } catch (Exception ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMIEfetuarVendaActionPerformed

    private void jMIAlterarAcampanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIAlterarAcampanteActionPerformed
        /**
         * telaAlterarCliente screen;
        try {
            screen = new telaAlterarCliente();
            screen.setVisible(true);
            dispose();
        } catch (Exception ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        * */
    }//GEN-LAST:event_jMIAlterarAcampanteActionPerformed

    private void jMIAlterarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIAlterarProdutoActionPerformed
        AlterarProdutoScreen screen;
        try {
            screen = new AlterarProdutoScreen();
            screen.setVisible(true);
            dispose();
        } catch (Exception ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMIAlterarProdutoActionPerformed

    private void jMIDeleteAcampanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIDeleteAcampanteActionPerformed
        /**
        telaDeletarCliente screen;
        try {
            screen = new telaDeletarCliente();
            screen.setVisible(true);
            dispose();
        } catch (Exception ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        * */
    }//GEN-LAST:event_jMIDeleteAcampanteActionPerformed

    private void jMIDeleteProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIDeleteProdutoActionPerformed
        /*telaDeletarProduto screen;
        try {
            screen = new telaDeletarProduto();
            screen.setVisible(true);
            dispose();
        } catch (Exception ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }//GEN-LAST:event_jMIDeleteProdutoActionPerformed

    private void jMIVisualizarAcampantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIVisualizarAcampantesActionPerformed
        VisualizarAcampantes screen;
        try {
            screen = new VisualizarAcampantes();
            screen.setVisible(true);
            dispose();
        } catch (Exception ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMIVisualizarAcampantesActionPerformed

    private void jMIVisualizarProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIVisualizarProdutosActionPerformed
        VisualizarProdutos screen;
        try {
            screen = new VisualizarProdutos();
            screen.setVisible(true);
            dispose();
        } catch (Exception ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMIVisualizarProdutosActionPerformed

    private void jMIVisualizarVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIVisualizarVendasActionPerformed
        /*telaVisualizarVendas screen;
        try {
            screen = new telaVisualizarVendas();
            screen.setVisible(true);
            dispose();
        } catch (Exception ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }//GEN-LAST:event_jMIVisualizarVendasActionPerformed

    private void jMIDepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIDepositoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMIDepositoActionPerformed

    private void jMIVisualizarSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIVisualizarSaldoActionPerformed
        VisualizarSaldoAcampantes screen;
        try {
            screen = new VisualizarSaldoAcampantes();
            screen.setVisible(true);
            dispose();
        } catch (Exception ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMIVisualizarSaldoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Vizualizar;
    private javax.swing.JMenu jMAlteracoes;
    private javax.swing.JMenu jMCads;
    private javax.swing.JMenu jMDeletes;
    private javax.swing.JMenu jMEfetuar;
    private javax.swing.JMenuItem jMIAlterarAcampante;
    private javax.swing.JMenuItem jMIAlterarProduto;
    private javax.swing.JMenuItem jMICadastrarAcampante;
    private javax.swing.JMenuItem jMICadastrarProduto;
    private javax.swing.JMenuItem jMIDeleteAcampante;
    private javax.swing.JMenuItem jMIDeleteProduto;
    private javax.swing.JMenuItem jMIDeposito;
    private javax.swing.JMenuItem jMIEfetuarVenda;
    private javax.swing.JMenuItem jMILogout;
    private javax.swing.JMenuItem jMIVisualizarAcampantes;
    private javax.swing.JMenuItem jMIVisualizarProdutos;
    private javax.swing.JMenuItem jMIVisualizarSaldo;
    private javax.swing.JMenuItem jMIVisualizarVendas;
    private javax.swing.JMenuBar jMenuBar;
    // End of variables declaration//GEN-END:variables
}
